# Step 1: Instalation and Setup

In [ ]:
import tensorflow as tf
tf.__version__

'2.12.0'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Data Preprocessing

In [5]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d aakash50897/churn-modellingcsv
!unzip /content/churn-modellingcsv.zip

100% 262k/262k [00:00<00:00, 454kB/s]
100% 262k/262k [00:00<00:00, 454kB/s]
Archive:  /content/churn-modellingcsv.zip
  inflating: Churn_Modelling.csv     


In [6]:
data = pd.read_csv('/content/Churn_Modelling.csv')

In [7]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
X = data.drop(labels=['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)
y = data['Exited']

In [9]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [10]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
label_1 = LabelEncoder()
X['Geography'] = label_1.fit_transform(X['Geography'])

In [14]:
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [15]:
label_2 = LabelEncoder()
X['Gender'] = label_2.fit_transform(X['Gender'])

In [17]:
X.head(8)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   
5          645          2       1   44       8  113755.78              2   
6          822          0       1   50       7       0.00              2   
7          376          1       0   29       4  115046.74              4   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88

In [19]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])

In [21]:
X.head(8)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   
5          645       1   44       8  113755.78              2          1   
6          822       1   50       7       0.00              2          1   
7          376       0   29       4  115046.74              4          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1  
5               0        149756.71            0            1  
6               1         10062.80            0            0  
7               0        119346.88            1            0

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.36766974,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ...,  1.6612541 ,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.25280688,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ..., -0.1427649 ,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ..., -0.05082558,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.81456811,
         1.72572313, -0.57638802]])

In [27]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -1.01960511,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  0.79888291,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.72797953,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ..., -1.16591585,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ..., -0.41163463,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ...,  0.12593183,
         1.72572313, -0.57638802]])

# Step 3: Building the Model

In [34]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim=11))
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [35]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 72        
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dense_5 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


# Step 4: Training the model

In [37]:
model.fit(X_train, y_train.to_numpy(), batch_size=10, epochs=20)

Epoch 1/20
800/800 [==============================] - 11s 3ms/step - loss: 0.4967 - accuracy: 0.7870
Epoch 2/20
800/800 [==============================] - 3s 3ms/step - loss: 0.4342 - accuracy: 0.8083
Epoch 3/20
800/800 [==============================] - 2s 3ms/step - loss: 0.4228 - accuracy: 0.8184
Epoch 4/20
800/800 [==============================] - 2s 3ms/step - loss: 0.4181 - accuracy: 0.8240
Epoch 5/20
800/800 [==============================] - 2s 3ms/step - loss: 0.4134 - accuracy: 0.8279
Epoch 6/20
800/800 [==============================] - 2s 3ms/step - loss: 0.4081 - accuracy: 0.8314
Epoch 7/20
800/800 [==============================] - 3s 3ms/step - loss: 0.3987 - accuracy: 0.8367
Epoch 8/20
800/800 [==============================] - 2s 3ms/step - loss: 0.3831 - accuracy: 0.8453
Epoch 9/20
800/800 [==============================] - 2s 3ms/step - loss: 0.3659 - accuracy: 0.8536
Epoch 10/20
800/800 [==============================] - 2s 3ms/step - loss: 0.3534 - accuracy: 0.857

# Step 5: Model evaluation and prediction

In [38]:
test_loss, test_acc = model.evaluate(X_test, y_test.to_numpy())

63/63 [==============================] - 1s 4ms/step - loss: 0.3394 - accuracy: 0.8610


In [41]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

63/63 [==============================] - 0s 1ms/step


In [39]:
y_test = y_test.to_numpy()

In [44]:
i=11
print(y_pred[i], y_test[i])

[1] 1


In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1535   72]
 [ 206  187]]


In [46]:
acc_cm = accuracy_score(y_test, y_pred)
print(acc_cm)

0.861
